# Rustique configuration
mod_dir = "~/.config/Vintagestory/Mods"
# this is the latest version we want to download mods for
# in this case, any mod for version 1.20
pinned_game_version = "1.20.*"
# If you have mods in a folder, setting this option will auto-zip the file for you.
auto_zip_mod_files = false
# backup old versions of mods before updating them, IE dont delete
backup_mods = false

# How often to check the api for the latest versions of the game
sync_latest_game_versions_every = 24
# How often to update the search database from the api
sync_mod_search_info_every = 24

[[pkg]]
mod_id = "rustboundmagic"
pinned_version = "1.2.3"

[[pkg]]
mod_id = "alchemy"
pinned_version = "2.3.4"

[[pkg]]
mod_id = "armory"
# This prevents update from updating passed what is currently installed.
# This can be set in conjunction with pinned_version, but its effectively the same thing.
# Prevent_updates doesn't specify the version, so whatever is installed is what remains.
prevent_updates = true



[modpack]

# Modpack file will be downloaded from the mods website to here, at this point they are considered `installed`
# Once installed you can run `./Rustique mp enable modpack-name`
download_dir = "~/.config/rustique/modpacks/downloads"

# This location is for backing up your non-modpacks when enabling a modpack
# The entire Mods folder will be moved here and renamed with the date to keep uniqueness if you choose to have more than one
# By default, when you disable a modpack, the last folder created will be moved back into the ./config/VintagestoryData/Mods location
# You will be able to override this with flags
backup_dir = "~/.config/rustique/modpacks/backups/Mods-20250614"

[[alias]]
name = "custom_server"
mod_dir = "/opt/custom_server/Mods"
pinned_game_version = "1.20.5"

[[alias]]
name = "friends"
mod_dir = "/opt/servers/friends/Mods"
pinned_game_version = "1.20.*"

# each key is a column name that will show up in the list command table

# this is just an example of all valid column names
valid_columns_list = [
    "name",
    "mod_id",
    "version",
    "latest_version",
    "dependencies",
    "missing_dependencies",
    "last_changelog",
    "description",
    "website",
    "game_version",
    "last_updated_local",
    "last_updated_remote",
    "pinned_version",
    "has_backup",
    "filename"
]

valid_columns_search =[
    "mod_id",
    "asset_id",
    "downloads",
    "follows",
    "trending",
    "comments",
    "name",
    "summary",
    "modid_strs",
    "author",
    "url_alias",
    "side",
    "type",
    "tags",
    "last_released"
]


[table.list.headers]
name = ["red"]
mod_id = ["blue", "dim"]
#version = ["green", "blink", "other stupid thing here"]
#latest_version = []


[table.list.cells]
name.color = "yellow"
name.attribute = "bold"


mod_id = ["pink", "bold", "dim"]

[table.search.headers]
name = ["red", "bold"]


[table.search.cells]
name = ["green", "dim"]